# Generated by Django 3.0.6 on 2020-06-15 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_subtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salad',
            old_name='meal',
            new_name='salad_meal',
        ),
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dinner_meal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dinner_meal_id', to='menu.Meal')),
                ('dinner_platter_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_platter_size', to='menu.Size')),
            ],
        ),
    ]
