# Generated by Django 3.0.6 on 2020-06-15 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200615_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('num_of_topping', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pizza_num_of_topping', to='menu.NumOfTopping')),
                ('pizza_order_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_order_size', to='menu.Size')),
                ('pizza_order_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_order_type', to='menu.PizzaType')),
            ],
        ),
    ]
