# Generated by Django 3.0.6 on 2020-06-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_pizzaorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzaorder',
            old_name='num_of_topping',
            new_name='pizza_num_of_topping',
        ),
    ]
