# Generated by Django 3.0.6 on 2020-06-18 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20200615_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salad',
            name='salad_meal',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salad_meal', to='menu.Meal'),
        ),
    ]
