# Generated by Django 3.0.6 on 2020-06-18 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20200618_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salad',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salad',
            name='salad_meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salad_meal', to='menu.Meal'),
        ),
    ]
