# Generated by Django 3.0.6 on 2020-06-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
