# Generated by Django 3.0.6 on 2020-06-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='order_username',
        ),
    ]
