# Generated by Django 3.0.6 on 2020-06-20 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_auto_20200620_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubExtraOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_extra_option', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options_included', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('add_extra', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_extra', to='menu.AddExtra')),
                ('num_of_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.NumExtraOption')),
                ('options', models.ManyToManyField(blank=True, null=True, to='menu.SubExtraOption')),
                ('size', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_size', to='menu.Size')),
                ('sub_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_type_id', to='menu.SubType')),
            ],
        ),
    ]
