# Generated by Django 3.0.6 on 2020-06-20 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_sub_subextraoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='options',
        ),
        migrations.AddField(
            model_name='sub',
            name='option',
            field=models.ManyToManyField(blank=True, null=True, to='menu.SubExtraOption'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='num_of_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.NumExtraOption'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='options_included',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
