# Generated by Django 3.0.6 on 2020-06-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_auto_20200620_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='option',
            field=models.ManyToManyField(to='menu.SubExtraOption'),
        ),
    ]
