# Generated by Django 3.0.6 on 2020-06-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_auto_20200620_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='option',
            field=models.ManyToManyField(null=True, to='menu.SubExtraOption'),
        ),
    ]
