# Generated by Django 3.0.6 on 2020-06-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_auto_20200622_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_dinner_platter',
        ),
    ]
