# Generated by Django 3.0.6 on 2020-06-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_remove_cart_order_dinner_platter'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_dinner_platter',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
