# Generated by Django 3.0.6 on 2020-06-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_cart_order_dinner_platter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='pizza_topping',
            field=models.ManyToManyField(blank=True, null=True, to='menu.Topping'),
        ),
    ]
