# Generated by Django 3.0.6 on 2020-06-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_pizzaorder_pizza_topping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzaorder',
            name='pizza_topping',
        ),
    ]
