# Generated by Django 3.0.6 on 2020-06-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_remove_pizzaorder_pizza_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_pizza_topping',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_dinner_platter',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_extra',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_pasta',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_pizza',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_salad',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_selections',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_sub',
            field=models.CharField(max_length=30),
        ),
    ]
